export default {
  GET_CONTIFICATION_LIST: "GET_CONTIFICATION_LIST", //获取文章列表
  MARK_READ_BY_ID: "MARK_READ_BY_ID", //用ID标志已读
  MARK_ALL_READ: "MARK_ALL_READ", //全部标志已读
  START_LOADING: "START_LOADING", //开始加载
  START_LOGIN: "START_LOGIN", //开始登陆
  LOGIN_SUCCESS: "LOGIN_SUCCESS", //成功登陆
  DATA_SPIN_COMPLETE: "DATA_SPIN_COMPLETE",
  LOGIN_FAILED: "LOGIN_FAILED", //登陆失败
  CHANGER_AVATAR: "CHANGER_AVATAR", //更换头像
  SAVE_MODIFYPP_AVATAR: "SAVE_MODIFYPP_AVATAR"
};